name: Update README.md File and Publish to DockerHub
on:
  push:
    branches:
      - ci
    paths:
      - README.md

jobs:
  update-readme:
    name: Include Dockerfile content in README.md file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - run: cat README.md
      - run: cat Dockerfile
      - run: sed -i 's/DOCKERFILE_CONTENT/$(cat Dockerfile)/' README.md
      - run: cat README.md

  publish-readme:
    name: Publish READ.md to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_REPOSITORY }}
          provider: dockerhub
          short_description: ${{ github.event.repository.description }}
          readme_file: "README.md"
