name: Update README.md File and Publish to DockerHub
on:
  push:
    branches:
      - ci
    paths:
      - README.md

jobs:
  update-readme:
    name: Include Dockerfile content in README.md file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sed '/DOCKERFILE_CONTENT/r Dockerfile' README.md
      - run: git log
      - run: git remote -v
      - run: git config --list

  publish-readme:
    name: Publish READ.md to DockerHub
    needs: [update-readme]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_REPOSITORY }}
          provider: dockerhub
          short_description: ${{ github.event.repository.description }}
          readme_file: "README.md"
